predicates = [
  "is", "is not", "is a", "is not a",
  "are", "are not", "are a", "are not a",
  "was", "was not", "was a", "was not a",
  "were", "were not", "were a", "were not a",
  "use", "uses", "used", "is an", "are an",
  "treat", "treats", "treated", "treated by", "treated with",
  "caused by", "cause", "causes", "caused",
  "prevent", "prevents", "prevented", "prevented by",
  "predispose", "predisposes", "predisposed", "predisposed by",
  "encourage", "encourages", "encouraged", "encouraged by",
  "discourage", "discourages", "discouraged", "discouraged by",
  "catalyze", "catalyzes", "catalyzed", "catalyzed by",
  "conjugate", "conjugates", "conjugated", "conjugated by",
  "connect", "connects to", "connects with", "connects", "connected", "connected with", "connected by",
  "considered as", "have","has", "had", "not have",
  "does not have", "did not have", "do not have",
  "never had", "never has", "never will have", "never can have",
  "can have", "may have", "should have", "can not have",
  "may not have", "should not have", "should never have",
  "must never have", "can't have", "could not have", "couldn't have",
  "consume", "consumes", "consumed", "consumed by",
  "create", "creates", "created", "created by",
  "acetylate", "acetylates", "acetylated", "acetylated by",
  "deacetylate", "deacetylates", "deacetylated", "deacetylated by",
  "absorb", "absorbs", "absorbed", "absorbed by",
  "accelerate", "accelerates", "accelerated", "accelerated by",
  "decelerate", "decelerates", "decelerated", "decelerated by",
  "accumulate", "accumulates", "accumulated", "accumulated by",
  "act as", "acts as", "acted as",
  "activate", "activates", "activated", "activated by",
  "deactivate", "deactivates", "deactivated", "deactivated by",
  "adapt", "adapts", "adapted", "adapted by",
  "add", "adds", "added", "added by",
  "affect", "affects", "affected", "affected by",
  "aggregate", "aggregates", "aggregated", "aggregated by",
  "believe", "believes", "believed",
  "associate", "associates", "associated", "associated with",
  "involved in", "not involved in",
  "involved with", "not involved with",
  "can", "cannot", "can not", "able to", "not able to",
  "inable to", "unable to", "find", "found",
  "found to", "not find", "not found", "not found to",
  "found to", "found in", "not found in",
  "responsible for", "not responsible for", "composed of",
  "not composed of", "describe", "describes", "described",
  "such as"
]
